### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by Zaedus** [ruslang02/discord-qt#23]
Running into this issue after downloading the deb and also building manually from the git source.
```
TypeError: Cannot read property 'length' of null
    at Object.READY (/tmp/discord-qt/dist/index.js:2:1737708)
    at WebSocketManager.handlePacket (/tmp/discord-qt/dist/index.js:2:1723888)
    at WebSocketShard.onPacket (/tmp/discord-qt/dist/index.js:2:444476)
    at WebSocketShard.onMessage (/tmp/discord-qt/dist/index.js:2:442866)
    at WebSocket.n (/tmp/discord-qt/dist/index.js:2:1710442)
    at WebSocket.emit (events.js:315:20)
    at Receiver.N (/tmp/discord-qt/dist/index.js:2:426463)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/tmp/discord-qt/dist/index.js:2:433049)
    at Receiver.getData (/tmp/discord-qt/dist/index.js:2:432289)
```

**Comment by ruslang02** [comment]
Should be fixed now, I wonder how this could happen... Do you have at least one user note on your account? Or, you have a note that references to a nonexistent user etc.?

**Comment by Zaedus** [comment]
I was just adding an account, that was it.

**Comment by ruslang02** [comment]
Everything is fine now? Gotta close the issue if it is resolved.

**Comment by Zaedus** [comment]
This solved the issue. Thanks for the quick response.
