### ISSUE TITLE
AppImage crashes with no such file error

### ISSUE THREAD

**Issue by CRISPYricePC** [ruslang02/discord-qt#30]
When starting up from the AppImage, I get this error in the console, and am then kicked into the nodejs console

```
[Patches] Applied 16 patches.
Welcome to Node.js v14.2.0.
Type ".help" for more information.
> QWidget::setMinimumSize: (ActionsMenu/NMenu) Negative sizes (220,-16) are not possible
Promise rejected. Error: ENOENT: no such file or directory, mkdir '/tmp/.mount_discorTxXovJ/dist/plugins'
    at Object.mkdirSync (fs.js:940:3)
    at PluginManager.recursiveSearch (/tmp/.mount_discorTxXovJ/dist/index.js:2:1971215)
    at /tmp/.mount_discorTxXovJ/dist/index.js:2:1971081
    at Array.map (<anonymous>)
    at PluginManager.reload (/tmp/.mount_discorTxXovJ/dist/index.js:2:1971068)
    at Application.start (/tmp/.mount_discorTxXovJ/dist/index.js:2:1823034) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/tmp/.mount_discorTxXovJ/dist/plugins'
} Promise {
  <rejected> Error: ENOENT: no such file or directory, mkdir '/tmp/.mount_discorTxXovJ/dist/plugins'
      at Object.mkdirSync (fs.js:940:3)
      at PluginManager.recursiveSearch (/tmp/.mount_discorTxXovJ/dist/index.js:2:1971215)
      at /tmp/.mount_discorTxXovJ/dist/index.js:2:1971081
      at Array.map (<anonymous>)
      at PluginManager.reload (/tmp/.mount_discorTxXovJ/dist/index.js:2:1971068)
      at Application.start (/tmp/.mount_discorTxXovJ/dist/index.js:2:1823034) {
    errno: -2,
    syscall: 'mkdir',
    code: 'ENOENT',
    path: '/tmp/.mount_discorTxXovJ/dist/plugins'
  }
}
> QComboBoxListView(0x5796780)  does not have a property named  "yBorder"
QComboBoxListView(0x5796780)  does not have a property named  "yBorder"
QComboBoxListView(0x5779970)  does not have a property named  "yBorder"
QComboBoxListView(0x5779970)  does not have a property named  "yBorder"
QComboBoxListView(0x5838220)  does not have a property named  "yBorder"
QComboBoxListView(0x5838220)  does not have a property named  "yBorder"
QComboBoxListView(0x583afc0)  does not have a property named  "yBorder"
QComboBoxListView(0x583afc0)  does not have a property named  "yBorder"
QComboBoxListView(0x5845c70)  does not have a property named  "yBorder"
QComboBoxListView(0x5845c70)  does not have a property named  "yBorder"
QScrollBar(0x537d9e0)  does not have a property named  "yMarginRight"
QScrollBar(0x537e3e0)  does not have a property named  "yMarginRight"
QScrollBar(0x537d9e0)  does not have a property named  "yMarginRight"
QScrollBar(0x537e3e0)  does not have a property named  "yMarginRight"
QScrollBar(0x4bde460)  does not have a property named  "yMarginRight"
QScrollBar(0x4b94ed0)  does not have a property named  "yMarginRight"
QScrollBar(0x4bde460)  does not have a property named  "yMarginRight"
QScrollBar(0x4b94ed0)  does not have a property named  "yMarginRight"
QComboBoxListView(0x4bcf4f0)  does not have a property named  "yBorder"
QComboBoxListView(0x4bcf4f0)  does not have a property named  "yBorder"
```

Not sure if the Qt warnings are related. I think something has clearly gone wrong with fileio

**Comment by ruslang02** [comment]
Should be easily fixable via an option in `mkdirSync` call, will look into that
