### ISSUE TITLE
Crash on LMDE2 (Debian 10 based)

### ISSUE THREAD

**Issue by frogwoosh** [ruslang02/discord-qt#33]
```
TypeError: Cannot read property 'cache' of undefined
    at MessageCreateAction.handle (/home/user/src/discord-qt/dist/index.js:2:313550)
    at Object.e.exports [as MESSAGE_CREATE] (/home/user/src/discord-qt/dist/index.js:2:363583)
    at WebSocketManager.handlePacket (/home/user/src/discord-qt/dist/index.js:2:350293)
    at WebSocketShardPatch.onPacket (/home/user/src/discord-qt/dist/index.js:2:355658)
    at WebSocketShardPatch.onMessage (/home/user/src/discord-qt/dist/index.js:2:354048)
    at WebSocket.n (/home/user/src/discord-qt/dist/index.js:2:2085522)
    at WebSocket.emit (events.js:315:20)
    at Receiver.N (/home/user/src/discord-qt/dist/index.js:2:2117048)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/home/user/src/discord-qt/dist/index.js:2:2099391)

```

**Comment by ruslang02** [comment]
When does it occur? It is most likely caused by the group dms which cause the client to crash, #27 aims to fix that, check if the problem is present there
